name: 'Run tests'

on: pull_request

permissions:
  contents: read

jobs:
  node-latest:
    uses: ./.github/workflows/test-node.yaml
    with:
      node: latest

  node-12:
    uses: ./.github/workflows/test-node.yaml
    with:
      node: 12

  node-14:
    uses: ./.github/workflows/test-node.yaml
    with:
      node: 14

  node-16:
    uses: ./.github/workflows/test-node.yaml
    with:
      node: 16
