name: Test a node version

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  node:
    concurrency: ${{ github.ref }}${{ inputs.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ inputs.node }}

      - name: Install
        run: npm install

      - name: Run tests
        run: npm test
